In [1]:
import pandas as pd
Raw_Data = pd.read_csv('Raw_Data.csv')
Raw_Data.head()

   Target(Class)     GyroX     GyroY     GyroZ      AccX      AccY      AccZ
0              1 -0.923664  3.694656  0.824427  0.162598 -0.086670 -0.969482
1              1 -0.908397  4.534351  0.832061  0.175781 -0.100586 -1.013184
2              1  0.786260  3.969466  0.587786  0.322754 -0.140381 -0.911621
3              1  0.335878  4.564885 -0.251908  0.480225 -0.226807 -0.936768
4              1  3.351145  2.694656 -0.106870  0.426025 -0.253906 -0.950195

In [2]:
df = pd.concat([Raw_Data.iloc[:, 0], Raw_Data.iloc[:, 4], Raw_Data.iloc[:, 5], Raw_Data.iloc[:, 6]], axis = 1)
df.rename(columns = {'Target(Class)' : 'Label'}, inplace = True)
df.head()

   Label      AccX      AccY      AccZ
0      1  0.162598 -0.086670 -0.969482
1      1  0.175781 -0.100586 -1.013184
2      1  0.322754 -0.140381 -0.911621
3      1  0.480225 -0.226807 -0.936768
4      1  0.426025 -0.253906 -0.950195

In [3]:
df1 = pd.DataFrame(df[df['Label'] == 1].iloc[:, 1:4] * 9.81)
df1 = df1.reset_index(drop = True)
df1.head()

       AccX      AccY      AccZ
0  1.595083 -0.850232 -9.510623
1  1.724414 -0.986748 -9.939331
2  3.166216 -1.377136 -8.943003
3  4.711003 -2.224973 -9.189690
4  4.179309 -2.490820 -9.321416

In [4]:
df2 = pd.DataFrame(df[df['Label'] == 2].iloc[:, 1:4] * 9.81)
df2 = df2.reset_index(drop = True)
df2.head()

       AccX      AccY       AccZ
0  1.592688 -0.658630  -9.544153
1  3.103945 -1.302891  -9.137000
2  1.686094 -0.718506  -9.244775
3  3.314707 -1.539998 -10.700947
4  2.517166 -1.662144  -9.086704

In [5]:
df3 = pd.DataFrame(df[df['Label'] == 3].iloc[:, 1:4] * 9.81)
df3 = df3.reset_index(drop = True)
df3.head()

       AccX      AccY      AccZ
0  2.224973 -1.298101 -9.912986
1  3.250042 -1.429827 -9.793235
2  4.232000 -2.057322 -9.850715
3  3.630850 -0.608335 -8.840017
4  3.580554 -1.298101 -9.821975

In [6]:
df4 = pd.DataFrame(df[df['Label'] == 4].iloc[:, 1:4] * 9.81)
df4 = df4.reset_index(drop = True)
df4.head()

       AccX      AccY       AccZ
0  0.553250  0.038320 -10.152488
1 -0.158071  1.094524  -9.105864
2  0.122146  0.210762  -9.067544
3  0.280217  0.450264  -9.829160
4  1.027463 -0.241897 -10.368040

In [7]:
df1.to_csv('Data/SlicedData/df1.csv', sep = ',')
df2.to_csv('Data/SlicedData/df2.csv', sep = ',')
df3.to_csv('Data/SlicedData/df3.csv', sep = ',')
df4.to_csv('Data/SlicedData/df4.csv', sep = ',')