In [1]:
import pandas as pd
Raw_Data = pd.read_csv('Raw_Data.csv')
Raw_Data.head()

   Target(Class)     GyroX     GyroY     GyroZ      AccX      AccY      AccZ
0              1 -0.923664  3.694656  0.824427  0.162598 -0.086670 -0.969482
1              1 -0.908397  4.534351  0.832061  0.175781 -0.100586 -1.013184
2              1  0.786260  3.969466  0.587786  0.322754 -0.140381 -0.911621
3              1  0.335878  4.564885 -0.251908  0.480225 -0.226807 -0.936768
4              1  3.351145  2.694656 -0.106870  0.426025 -0.253906 -0.950195

In [2]:
df = pd.concat([Raw_Data.iloc[:, 0], Raw_Data.iloc[:, 4], Raw_Data.iloc[:, 5], Raw_Data.iloc[:, 6]], axis = 1)
df.rename(columns = {'Target(Class)' : 'Label'}, inplace = True)
df.head()

   Label      AccX      AccY      AccZ
0      1  0.162598 -0.086670 -0.969482
1      1  0.175781 -0.100586 -1.013184
2      1  0.322754 -0.140381 -0.911621
3      1  0.480225 -0.226807 -0.936768
4      1  0.426025 -0.253906 -0.950195

In [3]:
df1 = pd.DataFrame(df[df['Label'] == 1].iloc[:, 1:4])
df1 = df1.reset_index(drop = True)
df1.head()

       AccX      AccY      AccZ
0  0.162598 -0.086670 -0.969482
1  0.175781 -0.100586 -1.013184
2  0.322754 -0.140381 -0.911621
3  0.480225 -0.226807 -0.936768
4  0.426025 -0.253906 -0.950195

In [4]:
df2 = pd.DataFrame(df[df['Label'] == 2].iloc[:, 1:4])
df2 = df2.reset_index(drop = True)
df2.head()

       AccX      AccY      AccZ
0  0.162354 -0.067139 -0.972900
1  0.316406 -0.132812 -0.931396
2  0.171875 -0.073242 -0.942383
3  0.337891 -0.156982 -1.090820
4  0.256592 -0.169434 -0.926270

In [5]:
df3 = pd.DataFrame(df[df['Label'] == 3].iloc[:, 1:4])
df3 = df3.reset_index(drop = True)
df3.head()

       AccX      AccY      AccZ
0  0.226807 -0.132324 -1.010498
1  0.331299 -0.145752 -0.998291
2  0.431396 -0.209717 -1.004150
3  0.370117 -0.062012 -0.901123
4  0.364990 -0.132324 -1.001221

In [6]:
df4 = pd.DataFrame(df[df['Label'] == 4].iloc[:, 1:4])
df4 = df4.reset_index(drop = True)
df4.head()

       AccX      AccY      AccZ
0  0.056396  0.003906 -1.034912
1 -0.016113  0.111572 -0.928223
2  0.012451  0.021484 -0.924316
3  0.028564  0.045898 -1.001953
4  0.104736 -0.024658 -1.056885

In [7]:
df1.to_csv('Data/SlicedData/df1.csv', sep = ',')
df2.to_csv('Data/SlicedData/df2.csv', sep = ',')
df3.to_csv('Data/SlicedData/df3.csv', sep = ',')
df4.to_csv('Data/SlicedData/df4.csv', sep = ',')